[phases.setup]
nixPkgs = ['nodejs', 'openssl']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate', 'npx prisma db push --accept-data-loss || true', 'npm run build']

[start]
cmd = 'npm run start:all'
